layout_spectrum: 0.7031063
color:
  saturation: 0.4868578
  brandStrength: 0.9898446
  lightness: 0.4868578
  rhythmicContrast: 0.4999999
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
typography_spectrum: 0.9898446
name: Prvtsl
